### ISSUE TITLE
typo in status report load_wrangle_run script

### ISSUE THREAD

**Issue by swmpkim** [NOAA-OCM/SWMPrExtension#32]
Not in the SWMPrExtension package, but in the Status Report script 01_Load_Wrangle_Run.R: line 79, one of the ways to calculate DIN, has `no2f` included twice. One of these should be `no3f`.

**Comment by padilla410** [comment]
Hi Kim,

I have resolved this and sent the updated files to both Dave and CDMO. You should see the correction the next time you receive a package from CDMO.
