### ISSUE TITLE
improve y-axis for barometric pressure plots

### ISSUE THREAD

**Issue by swmpkim** [NOAA-OCM/SWMPrExtension#36]
I'm not sure if this should be one issue, or if it should be split out for each function/plot type; feel free to close and/or rejigger as needed. In plots of barometric pressure, the y-axis always starts at 0, which I assume was intentional for most parameters. But for bp, where values are generally >1000, it's problematic. Would be great if we could let ggplot choose the default axis limits for this parameter (and maybe that was the case - I ran these using ggplot 3.x and that messed up some of the other plot formatting).
 
Affected output files from the status reports are in these directories:
boxplot_raw
boxplot_seasonal
boxplot_seasonal_w_target_yr
range_annual
range_historical_daily
range_historical_seasonal
trend_dot_plot

**Comment by padilla410** [comment]
Thanks, Kim. Let's keep this as one issue. It's likely the same fix for all functions.
