### ISSUE TITLE
Remove me from editing group

### ISSUE THREAD

**Issue by padilla410** [NOAA-OCM/SWMPrExtension#37]
I think I should be removed as a active collaborator. I can submit changes via pull requests instead.

**Comment by DaveEslinger** [comment]
Done.  Thanks for pointing that out.  It was an oversight on my part.  You now should have read permission only, but still be a collaborator.  Let me know if that is why you see from your end.

**Comment by padilla410** [comment]
Hi Dave,

I think you did it. I can no longer see the settings menu.
