### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [NOAA-OCM/SWMPrExtension#49]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming broom 0.7.0 release and found new errors/test failures for the CRAN version of this package, which seem to result from our decision to no longer export rowwise dataframe tidiers (for maintainability purposes). I've pasted the results below:

*   checking examples ... ERROR
    ```
    Running examples in ‘SWMPrExtension-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: seasonal_dot
    > ### Title: Seasonal Dot Plot
    > ### Aliases: seasonal_dot seasonal_dot.swmpr
    > 
    > ### ** Examples
    > 
    > dat_wq <- elksmwq
    > #dat_wq <- subset(dat_wq, subset = c('2010-01-01 0:00', '2017-01-01 0:00'))
    > dat_wq <- qaqc(dat_wq, qaqc_keep = c(0, 3, 5))
    > 
    > x <-
    +   seasonal_dot(dat_wq, param = 'do_mgl'
    +                , lm_trend = TRUE
    +                , lm_lab = TRUE
    +                , plot_title = TRUE)
    Error: No tidy method for objects of class rowwise_df
    Execution halted
    ```

To help with fixes: the most recently exported definitions of the rowwise dataframe tidiers can be found [here](https://github.com/tidymodels/broom/blob/0.5.6/R/dplyr-rowwise-df-tidiers.R).🙂

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!

**Comment by DaveEslinger** [comment]
Thanks, Simon, for the advance notice.  Fixed with the nest-map approach in release v1.1.5.
